sudo: false
language: node_js
node_js:
- '0.12'
script:
- bash ./scripts/deploy.sh
env:
  global:
  - GITHUB_REF: github.com/cchandurkar/Travis-Test
  - secure: gwgQgt9Ryxpu0EFXgQ5XUlGnp4XfgBMMwnpx2d0JGjTovVX4dNUr9uev+UEIdUiKokns4b2XzIsq1zuqOWt0PALgW+L783YJRy06Mi36YvMvtYwjhTI2l6Wub58AqVVy5CawuCjerEtKHRu1v4sVKutHUPCnjdL+AlPBv0f9Lz2reQqldN9TjDaWueEtqQCsNADbWXjZOiWH7YZUZGCQy167c3AvNiXCQx8bxYwuxSFWNfZP5Y9eXrKSOIvbx86DKksIIZjoGNlWZ6/xbTKOoQVgWKmSzdKzO5/aFyiDftsEqdi8qbW18qR+FZ2Cw6P10kfBaOkYyTZeoHYtoqI1fLzgZxjmZSlOIcV4tcjX2xCVz/URAA9tLzDQaQgABrfKx4wGvL7nf3ZuT6QugNh7ygwDq6C2HgTQsfDCgK6ArxINkJDcJ+PL9wOmEWxEtspzFdVUcGE8rn/ZtoJI5r/NM9vE06ISeCsPa1qY3CaPy2T5wqd2EnTGRUfb2Khe3T8T9DdcltBtnObXjcxJ16NMsbZwf/JW5QlowGAEVNKoPVx18VYoEcTvlR3bSwuXPraiuIP51pl4MayX5YSj6LzrKE0J77jJ7pLzV94lYEY+A13DR5b62WO4g2t11Nc8EME9aPMWIeq0JTPwHqdbtCM8sTDiRWjwjjFlDI0L4vrhdao=
  - COMMIT_AUTHOR_EMAIL: cchandurkar@gmail.com
  - COMMIT_AUTHOR_NAME: Travis CI
deploy:
  on:
    tags: true
    branch: master
  api_key:
    secure: L72heunqL1NaOfVHpVDzldGsUyCHQnswJC3pyhjf3WW8p2rOiaCbTpAYSK1p4Q9Ud1kTowwMW5OeCwa2PKNbtzupVuGIt0v6xKdDfGZXE1BE2/9eyQHBxvhSafMsI2ABMWkV7m/NN8BRqGgjJsOpID3YQqZZ/+LPga/WsUUOvpzX2BbLILMMmQGDwyZxLI2J/BY6BU4O4i6LLuh1/zi12+0j/xL6prmgfbUygzCfut9QVYHmetcS5VTT0m7BdRFOke+8wZRByFYSuNEq96YxKsfr8tSVrusja1Qvf2pE8ZQn5urBIMR2aVRGlj9MJD3RHuSU01KE4tm66fEkfYspO4QG3mmkqo3njLEYkpvq+YbgTZL+/joOenrSnmJALKGqWieoVtDO4kgF8zrUapmkShX0Gk3hRISWznXGph1CAkbvXL7oRKMF6mS8q2k3gBVJXhaSLQAy4ijhzWaBwe6MNEYH5cXvnzYpZlWRTcXt5/GVbQ1rSaFtnVTwlq5SHOP7eBBmIMjI0LoB6pgXwNBztrUyPCRmJkhP7LI0MpKwYKhHWOUfwTM7F1ZVN2mkHie3irjL3hMuysWDd9TK6VrnzIOVC9H0Afa4bGoR362y+kNGOGF7HQAzDhsTL20PtrogWGfxF4w7r8BuW/YZ/sQQTtHnNRb/6QKLFSLzOvwEiIs=
